### ISSUE TITLE
Suitable icon for the repository

### ISSUE THREAD

**Issue by istedee** [Mikkeep/ctf-cheat-sheet#1]
As I cannot change the social media preview of the repository, I am suggesting that it would be changed to the one below.

![bob_nice](https://github.com/Mikkeep/ctf-cheat-sheet/assets/55876929/6c12984e-db87-448c-bbae-e66ce677d08a)

Link provides instructions if needed: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview

**Comment by Mikkeep** [comment]
You have brought great value to stakeholders, due to this awesome contribution.
I thank you sincerely, and close the issue as resolved.

#Bob
